name: End-to-End Local DevOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Security Scan (SAST)
      run: |
        pip install bandit
        bandit -r app.py

  local-deploy-and-test:
    needs: lint-and-test
    runs-on: self-hosted # Roda no seu Windows (PowerShell)
    steps:
    - uses: actions/checkout@v4

    - name: Enviar Imagem Docker para o ambiente do Minikube
      run: |
        minikube image build -t telemetry-app:local .

    - name: Executar Terraform (IaC)
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Executar Automacao e Auditoria com Ansible (via WSL)
      run: |
        # O Windows repassa a execucao para dentro do Ubuntu/WSL, resolvendo o problema do CP1252!
        wsl pip install ansible
        wsl ansible-playbook playbook.yml