name: End-to-End Local DevOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Security Scan (SAST)
      run: |
        pip install bandit
        bandit -r app.py

  local-deploy-and-test:
    needs: lint-and-test
    runs-on: self-hosted # Vai rodar na sua máquina Windows usando o Runner local
    steps:
    - uses: actions/checkout@v4

    - name: Enviar Imagem Docker para o ambiente do Minikube
      run: |
        # Usa o build nativo do Minikube para ignorar incompatibilidades da CLI do Docker local
        minikube image build -t telemetry-app:local .

    - name: Executar Terraform (IaC)
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Executar Automação e Auditoria com Ansible
      run: |
        # Instala o Ansible localmente
        pip install ansible
        
        # Força o PowerShell a usar encoding UTF-8 nesta sessão
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $env:PYTHONIOENCODING='utf-8'
        
        # Agora o Ansible roda sem chiar
        ansible-playbook playbook.yml